#!/usr/bin/env python3
"""从和风天气 China-City-List 生成 lib/infrastructure/geo/china_birth_places_data.dart"""

import csv
import io
import urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/qwd/LocationList/master/China-City-List-latest.csv"
OUT = Path(__file__).resolve().parent.parent / "lib/infrastructure/geo/china_birth_places_data.dart"
CACHE = Path(__file__).resolve().parent / "china_cities_raw.txt"


def main() -> None:
    if CACHE.is_file():
        raw = CACHE.read_text(encoding="utf-8")
    else:
        req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0"})
        raw = urllib.request.urlopen(req, timeout=120).read().decode("utf-8-sig")
        CACHE.write_text(raw, encoding="utf-8")
    lines = raw.splitlines()
    csv_lines = []
    for line in lines:
        if line.startswith("Location_ID,") or (
            line and line[0].isdigit() and line.split(",")[0].isdigit()
        ):
            csv_lines.append(line)
    if not csv_lines:
        raise SystemExit("No CSV rows found in source")
    reader = csv.DictReader(csv_lines)
    places: list[tuple[str, str, float, float]] = []
    seen: set[str] = set()

    for row in reader:
        name_zh = (row.get("Location_Name_ZH") or "").strip()
        prov = (row.get("Adm1_Name_ZH") or "").strip()
        adm2 = (row.get("Adm2_Name_ZH") or "").strip()
        if not name_zh:
            continue
        try:
            lat = float(row["Latitude"])
            lon = float(row["Longitude"])
        except (KeyError, ValueError):
            continue
        if lon < 73 or lon > 136:
            continue

        label = _format_label(name_zh, prov, adm2)
        if label in seen:
            continue
        seen.add(label)

        prov_short = _short_province(prov)
        places.append((label, prov_short, lon, lat))

    places.sort(key=lambda x: (x[1], x[0]))

    buf = io.StringIO()
    buf.write(
        "// GENERATED by tool/generate_birth_places.py — do not edit by hand.\n"
        "import '../../domain/entities/birth_place.dart';\n\n"
        "const List<BirthPlace> kChinaBirthPlacesData = [\n"
    )
    for label, prov, lon, lat in places:
        label_esc = label.replace("'", "\\'")
        prov_esc = prov.replace("'", "\\'")
        buf.write(
            f"  BirthPlace(name: '{label_esc}', province: '{prov_esc}', "
            f"longitude: {lon:.4f}, latitude: {lat:.4f}),\n"
        )
    buf.write("];\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(buf.getvalue(), encoding="utf-8")
    print(f"Wrote {len(places)} places to {OUT}")


def _short_province(prov: str) -> str:
    for suffix in (
        "维吾尔自治区",
        "壮族自治区",
        "回族自治区",
        "特别行政区",
        "自治区",
        "省",
        "市",
    ):
        if prov.endswith(suffix):
            return prov[: -len(suffix)]
    return prov


def _format_label(name_zh: str, prov: str, adm2: str) -> str:
    if name_zh in ("北京", "上海", "天津", "重庆"):
        return f"{name_zh}市"
    if name_zh.endswith(("市", "县", "区", "盟", "州", "旗", "地区")):
        base = name_zh
    else:
        base = name_zh

    if base.endswith("市") or base.endswith("盟") or base.endswith("州"):
        return base

    if prov in ("北京市", "上海市", "天津市", "重庆市") and prov == adm2:
        return f"{prov}{base}区" if not base.endswith("区") else f"{prov}{base}"

    if adm2.endswith("市") and base != adm2:
        return f"{adm2}{base}"

    if prov and not base.startswith(prov[:2]):
        return f"{prov}{base}" if len(base) <= 3 else base

    return f"{base}市" if len(base) <= 2 else base


if __name__ == "__main__":
    main()
